### PR TITLE
Publish WinP Javadoc

### PR DESCRIPTION
**Pull request by basil**

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
That script seems to be pulling from the wrong url

e.g. 
this works:
https://repo.jenkins-ci.org/releases/org/jenkins-ci/main/jenkins-core/2.361.1/jenkins-core-2.361.1-javadoc.jar

but not
https://repo.jenkins-ci.org/releases/org/jenkins-ci/main/jenkins-core/2.361/jenkins-core-2.361-javadoc.jar

**Comment by basil** [comment]
Whatever problems are occurring in the above CI build, they are certainly not caused by the addition of WinP in this PR.

**Comment by dduportal** [comment]
I openned an issue about the failing build on the main branch: https://github.com/jenkins-infra/javadoc/issues/48.
I need help to understand and solve it.

**Review by NotMyFault — APPROVED** [review]

**Comment by basil** [comment]
Could have been merged a week ago without making the main branch any worse than it was at that time.

**Pull request merged**
