### PR TITLE
Generate Javadoc from LTS release, not LTS baseline

### LINKED ISSUE #48: Build failing with https://repo.jenkins-ci.org/releases/org/jenkins-ci/main/jenkins-core/2.361/jenkins-core-2.361-java Not Found.
The build is failing on ci.jenkins.io (and also on trusted.ci.jenkins.io) for this project:

- Failing Build: https://ci.jenkins.io/job/Infra/job/javadoc/job/master/367/
- Error message:

```console
05:23:09  LTS_RELEASES is not defined. Pulling all releases from Jenkins Artifactory
05:23:09    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
05:23:09                                   Dload  Upload   Total   Spent    Left  Speed
05:23:09  
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2472    0  2472    0     0  17531      0 --:--:-- --:--:-- --:--:-- 17657
05:23:09  >> Found release 2.361
05:23:09  https://repo.jenkins-ci.org/releases/org/jenkins-ci/main/jenkins-core/2.361/jenkins-core-2.361-javadoc.jar:
05:23:09  2022-09-12 05:23:09 ERROR 404: Not Found.
```

The last successful build was 7 days ago: https://ci.jenkins.io/job/Infra/job/javadoc/job/master/366

### PR DESCRIPTION
**Pull request by basil**
Like https://github.com/jenkins-infra/core-taglibs-report-generator/pull/16 but for `jenkins-infra/javadoc`. Switches to generating Javadoc for the actual LTS release rather than the baseline for that LTS release. So instead of trying to use the broken 2.361 we generate the site from the working 2.361.2.

Fixes #48

### CODE REVIEW

**Comment by basil** [comment]
CC @timja

**Review by timja — APPROVED** [review]
Personally I would probably just use the latestStable text file on Jenkins.io but this was already doing funky things.


Thanks!

**Comment by basil** [comment]
Well sure but this script was trying to compute not just the latest stable but rather the last 10 stable releases. Funky indeed =)

**Comment by lemeurherve** [comment]
Thanks @basil for the fix and the improvement!

**Comment by dduportal** [comment]
Thanks a lot for this fix!

**Comment by basil** [comment]
You are welcome for this courtesy. In the future, the expectation is that the main branch of this repository is kept in a stable state by members of the infrastructure team.

**Pull request merged**
